### ISSUE TITLE
thunderclap database 

### ISSUE THREAD

**Issue by ansarizafar** [cloudflare/production-saas#14]
@lukeed Why not use thunderclap(A database on top of Workers KV) for this project. 

https://github.com/anywhichway/thunderclap

**Comment by lukeed** [comment]
Hey, thanks for the suggestion, but the purpose of this project (and for using KV specifically) is to show people how to use the native tech and the demonstrate the raw data organization. That's a lot harder to follow & understand when everything is living behind a bunch of abstraction.

I'm sure the library is great! But this would be like trying to teach someone how the DOM works by teaching them React or Svelte first. Those are tools that facilitate the DOM operations, but if thats all a user knows, they still don't know what's going on underneath.

**Comment by ansarizafar** [comment]
This project is already using a third party web framework(Worktop) to simplify code. KV requires lots of boilerplate code in each project which is against the goal of cloudflare of making life easy for the developers. 

Cloudflare is a complete platform, the only missing piece is a native database. The purpose of this suggestion is that we should have an abstraction layer like thunderclap on top of KV or durable storage to avoid repetitive code in each project and which can easily be used as a database. 

I request you to please check thunderclap repo when you get time. The project is not maintained by the author anymore but he is willing to change the licence.

Anyways,I am a great fan of @lukeed work and I respect your opinion.

**Comment by lukeed** [comment]
Worktop is only used for the routing, which is an expectation for any application. There are a collection of other utilities used throughout too, but it's (at most) 100 lines of worktop code used by this project. Very very minimal and still easy to follow

**Comment by NaNorNull** [comment]
I put this together for the Summer Challenge to help in reducing my 
boilerplate. I didn't realize that Thunderclap was out there. It is 
much, much more basic than Thunderclap, but might have something useful 
in it since it and is only about 400 lines of code...

https://github.com/NaNorNull/cfkvdb/blob/main/cf-kv-db.js

**Comment by NaNorNull** [comment]
As an FYI, I have gotten it working with the new Functions capability 
for Pages:

https://github.com/NaNorNull/cfkvdb/tree/main/functions/query

It is a very nice new capability.
